### ISSUE TITLE
Unable to load source code solution 

### ISSUE THREAD

**Issue by ubidev** [chris-tomich/Glyma#1]
Hi
I got the glyma compiled solution installed and working on a windows server2012r2/sql2012sp3/sp2013ent combo. all is good and thank you for this amazing tool

Now, I'd like to contribute to the evolution of this tool and to that purpose, I installed vs2015ent update 3 and the latest telerik silverlight controls, other dependencies and updates.

Unfortunately , when I load the Glyma.SharePoint sln file, I get 2 projects that won't load properly: CompendiumMapSPService and SevenSigma.Loging . They both report that "the imported project c:\program......\msbuild.community.tasks.targets was not found... 

Can you please guide me in setting up this solution properly. I'll gladly contribute documentation on the matter for future hobyist like me. :)

thanks in advance

**Comment by chris-tomich** [comment]
Hi UbiDev,

I believe you need to install this NuGet package https://github.com/loresoft/msbuildtasks in order for it to start working.

Hopefully this solves the issue for you. :)

**Comment by ubidev** [comment]
Hi!
Just verified and I had already ran the “Install-Package MSBuildTasks” to no avail coz the project files of both failing to load projects depend on the msi version of the “MSBuild Community Tasks library”. 

But then, the msi itself fails to install correctly thanks to the infamous “Failed to open XML file, system error -2147024786” error!!!

In the end, extracting the content of the zip version of that tool to “"C:\Program Files (x86)\MSBuild\MSBuildCommunityTasks\” resolved the issue!

Now, that I can load the D:\src\3rdparty\Glyma\Glyma.SharePoint\Glyma.SharePoint.sln, the question is:

How do you build that complex project!

Thanks in advance for your time

UbiDev

**Comment by chris-tomich** [comment]
Hi Ubidev,

Each of the Visual Studio solutions build the various SharePoint Solution files and these are then deployed to a SharePoint deployment on which you can test.

If you haven't already done so, I recommend setting up a development SharePoint environment first. Once you have that running, deploy a pre-built set of binaries (contact me directly if you need these) to the SharePoint environment using the deployment instructions here https://github.com/chris-tomich/Glyma/tree/master/Documentation . You'll need to do this anyway when you do development but at least by doing it with a set of binaries that are guaranteed to work you'll be able to quickly get a feel for the architecture of Glyma and the components it relies on.

Glyma itself consists of a client-side program (both a part that is written in Silverlight and another part written in HTML5), a number of different SOAP web services on the SharePoint web front end, a SharePoint service application, and a number of databases (separate to SharePoint's databases) with a few SQL stored procedures. I'm not sure your current level of experience developing upon a Silverlight / SharePoint / MS SQL stack, but if you haven't done so already I'd recommend familiarising yourself with SharePoint architecture as Glyma is very tightly wound with this and even trying to debug client-side issues without an understanding of SharePoint architecture will make development very slow and difficult.

I hope that helps. :)

Kind Regards,
Chris Tomich

**Comment by chris-tomich** [comment]
Closing this as it's been stale for a while.
